import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { freshState, loadState, saveState } from '../src/state.mjs';
import { ensurePortalIdentity, portalStatus, writePortalConfig } from '../src/portal-client.mjs';
import { buildAssurancePortalSnapshot } from '../src/portal-assurance.mjs';
import { projectPaths } from '../src/paths.mjs';

const CLI = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'idleproof.mjs');
const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'idleproof-first-project-'));
const cleanup = (cwd) => { try { fs.rmSync(cwd, { recursive:true, force:true }); } catch {} };
const cli = (cwd, ...args) => execFileSync(process.execPath, [CLI, ...args], { cwd, encoding:'utf8' }).trim();

test('the enrollment identity is stable before any task, across processes, and creates no task', () => {
  const cwd = tmp();
  try {
    execFileSync('git', ['init', '-q'], { cwd });
    const first = cli(cwd, 'portal', 'identity');
    const second = cli(cwd, 'portal', 'identity');
    const json = JSON.parse(cli(cwd, 'portal', 'identity', '--json'));
    assert.match(first, /^[a-f0-9]{24}$/);
    assert.equal(second, first);
    assert.equal(json.projectLocalId, first);
    // Persisted state carries the identity; no session/task was fabricated to obtain it.
    assert.equal(fs.existsSync(projectPaths(cwd).state), true);
    assert.deepEqual(Object.keys(loadState(cwd).sessions), []);
    assert.equal(portalStatus(cwd).projectLocalId, first);
    // The local state directory is excluded from Git locally (not a tracked .gitignore edit).
    assert.match(fs.readFileSync(path.join(cwd, '.git', 'info', 'exclude'), 'utf8'), /^\.idleproof\/$/m);
    assert.equal(fs.existsSync(path.join(cwd, '.gitignore')), false);
    ensurePortalIdentity(cwd);
    assert.equal(fs.readFileSync(path.join(cwd, '.git', 'info', 'exclude'), 'utf8').match(/^\.idleproof\/$/gm).length, 1);
  } finally { cleanup(cwd); }
});

test('an existing persisted identity is kept, never regenerated by identity or configure', () => {
  const cwd = tmp();
  try {
    const state = freshState(cwd);
    state.createdAt = '2026-01-02T03:04:05.000Z';
    saveState(cwd, state);
    const before = portalStatus(cwd).projectLocalId;
    assert.equal(portalStatus(cwd).identityPersisted, true);
    assert.equal(ensurePortalIdentity(cwd).projectLocalId, before);
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'x'.repeat(32)}` });
    assert.equal(portalStatus(cwd).projectLocalId, before);
    assert.equal(loadState(cwd).createdAt, '2026-01-02T03:04:05.000Z');
  } finally { cleanup(cwd); }
});

test('status reports an uninitialized identity instead of a value that would change', () => {
  const cwd = tmp();
  try {
    const status = portalStatus(cwd);
    assert.equal(status.identityPersisted, false);
    assert.equal(status.projectLocalId, null);
    assert.match(cli(cwd, 'portal', 'status'), /identity not initialized yet/);
    const json = [JSON.parse(cli(cwd, 'portal', 'status', '--json')), JSON.parse(cli(cwd, 'portal', 'status', '--json'))];
    assert.deepEqual(json.map((value) => value.projectLocalId), [null, null]);
    fs.mkdirSync(projectPaths(cwd).dir, { recursive:true });
    fs.writeFileSync(projectPaths(cwd).portalConfig, '{ damaged'); // error branch
    assert.equal(portalStatus(cwd).projectLocalId, null);
    fs.rmSync(projectPaths(cwd).portalConfig);
    assert.equal(fs.existsSync(projectPaths(cwd).state), false);
  } finally { cleanup(cwd); }
});

test('status never pairs a persisted flag with an ID from a state it did not read', async () => {
  const { projectLocalId } = await import('../src/portal-snapshot.mjs');
  const realRead = fs.readFileSync;
  const race = (cwd, onFirstStateRead) => {
    let fired = false;
    fs.readFileSync = (file, ...args) => {
      if (!fired && file === projectPaths(cwd).state) { fired = true; onFirstStateRead(); }
      return realRead(file, ...args);
    };
    try { return portalStatus(cwd); } finally { fs.readFileSync = realRead; }
  };
  // A concurrent `reset` removes the persisted state exactly while status reads it.
  const resetCwd = tmp();
  try {
    saveState(resetCwd, freshState(resetCwd));
    const status = race(resetCwd, () => fs.rmSync(projectPaths(resetCwd).dir, { recursive:true, force:true }));
    assert.deepEqual([status.identityPersisted, status.projectLocalId], [false, null]);
  } finally { cleanup(resetCwd); }
  // Another process persists its own state exactly while status reads it.
  const createCwd = tmp();
  try {
    fs.mkdirSync(projectPaths(createCwd).dir, { recursive:true });
    let persisted = null;
    const status = race(createCwd, () => {
      saveState(createCwd, { ...freshState(createCwd), createdAt:'2026-01-01T00:00:00.000Z' });
      persisted = JSON.parse(realRead(projectPaths(createCwd).state, 'utf8'));
    });
    assert.equal(status.identityPersisted, status.projectLocalId !== null);
    if (status.projectLocalId !== null) assert.equal(status.projectLocalId, projectLocalId(persisted.project, persisted.createdAt));
  } finally { cleanup(createCwd); }
});

test('identity creation survives a reset that removes the state it just created', () => {
  const cwd = tmp();
  const realRead = fs.readFileSync;
  let resets = 0;
  try {
    // The first time the created state is read back, a concurrent reset removes it.
    fs.readFileSync = (file, ...args) => {
      if (resets === 0 && file === projectPaths(cwd).state && fs.existsSync(file)) { resets += 1; fs.rmSync(projectPaths(cwd).dir, { recursive:true, force:true }); }
      return realRead(file, ...args);
    };
    const status = ensurePortalIdentity(cwd);
    fs.readFileSync = realRead;
    assert.equal(resets, 1);
    assert.equal(status.identityPersisted, true);
    assert.match(status.projectLocalId, /^[a-f0-9]{24}$/);
    assert.equal(portalStatus(cwd).projectLocalId, status.projectLocalId);
  } finally { fs.readFileSync = realRead; cleanup(cwd); }
});

test('configure never reports an enrollment saved without a persisted identity', async () => {
  const { configurePortal } = await import('../src/portal-client.mjs');
  const cwd = tmp();
  const realRename = fs.renameSync;
  let resets = 0;
  try {
    // A concurrent reset removes the state right after the first enrollment is written.
    fs.renameSync = (from, to, ...args) => {
      const result = realRename(from, to, ...args);
      if (resets === 0 && to === projectPaths(cwd).portalConfig) {
        resets += 1;
        fs.rmSync(projectPaths(cwd).state, { force:true });
        fs.rmSync(projectPaths(cwd).stateBackup, { force:true });
      }
      return result;
    };
    const status = configurePortal(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'x'.repeat(32)}` });
    fs.renameSync = realRename;
    assert.equal(resets, 1);
    assert.equal(status.configured, true);
    assert.equal(status.identityPersisted, true);
    assert.match(status.projectLocalId, /^[a-f0-9]{24}$/);
    assert.equal(portalStatus(cwd).projectLocalId, status.projectLocalId);
  } finally { fs.renameSync = realRename; cleanup(cwd); }
});

test('configure never reports an enrollment that a reset removed before it was read back', async () => {
  const { configurePortal } = await import('../src/portal-client.mjs');
  const cwd = tmp();
  const realRead = fs.readFileSync;
  let resets = 0;
  try {
    // The state is read as persisted, then a concurrent reset removes the enrollment before it is read.
    fs.readFileSync = (file, ...args) => {
      if (resets === 0 && file === projectPaths(cwd).portalConfig && fs.existsSync(file)) { resets += 1; fs.rmSync(file, { force:true }); }
      return realRead(file, ...args);
    };
    const status = configurePortal(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'x'.repeat(32)}` });
    fs.readFileSync = realRead;
    assert.equal(resets, 1);
    assert.deepEqual([status.configured, status.identityPersisted, status.endpoint], [true, true, 'http://127.0.0.1:8787/api/v1/snapshots']);
    assert.equal(portalStatus(cwd).configured, true);
  } finally { fs.readFileSync = realRead; cleanup(cwd); }
});

function twoChanges() {
  const cwd = tmp();
  const state = freshState(cwd);
  const session = (id, changeId, at) => ({
    id, source:'run', status:'complete', startedAt:at, lastEventAt:at, completedAt:at, promptChars:0,
    touchedFiles:['app.py'], changed:{ added:1, deleted:0 }, concepts:{}, events:[],
    proof:{ changeId, diffSha256:'c'.repeat(64) }, taskSignals:{ file:'app.py' }
  });
  state.sessions.first = session('first', `dwchg_${'1'.repeat(24)}`, '2026-09-26T10:00:00.000Z');
  state.sessions.second = session('second', `dwchg_${'2'.repeat(24)}`, '2026-09-26T11:00:00.000Z');
  saveState(cwd, state);
  return cwd;
}
const envelopeFor = (changeId, points) => ({
  schema_version:'change-envelope-1', change_id:changeId,
  privacy:{ code_uploaded:false, contains_paths:false, contains_prompt_text:false },
  debt:{ report_schema:'debt-report-1', points, open_lineages:['DW-0123456789AB', 'DW-0123456789AC'], budget_passed:true }
});

test('debt of an earlier change stays attached to that change after a newer task', () => {
  const cwd = twoChanges();
  try {
    const first = buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8));
    assert.equal(first.change.changeId, `dwchg_${'1'.repeat(24)}`);
    assert.deepEqual(first.assurance.softwareDebt, { points:8, obligations:2, budgetPassed:true });
    const second = buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'2'.repeat(24)}`, 3));
    assert.equal(second.change.changeId, `dwchg_${'2'.repeat(24)}`);
    assert.notEqual(second.snapshotId, first.snapshotId);
  } finally { cleanup(cwd); }
});

test('a measurement of a change IdleProof did not complete is refused, not attached to the latest task', () => {
  const cwd = twoChanges();
  try {
    assert.throws(() => buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'3'.repeat(24)}`, 8)), /matches no change completed by IdleProof/);
    assert.equal(fs.existsSync(projectPaths(cwd).portalQueue), false);
  } finally { cleanup(cwd); }
});

// A Portal emulator with the real retransmission rule: same id + same body → duplicate,
// same id + different body → 409 SNAPSHOT_CONFLICT.
function portalEmulator({ loseFirstAck = false } = {}) {
  const stored = new Map();
  const bodies = [];
  let calls = 0;
  const fetchImpl = async (_url, { body }) => {
    calls += 1;
    bodies.push(body);
    const snapshot = JSON.parse(body);
    const known = stored.get(snapshot.snapshotId);
    const reply = (status, value) => ({ status, text: async () => JSON.stringify(value) });
    if (known !== undefined && known !== body) return reply(409, { error:{ code:'SNAPSHOT_CONFLICT' } });
    const fresh = known === undefined;
    stored.set(snapshot.snapshotId, body);
    if (loseFirstAck && calls === 1) throw Object.assign(new Error('connection reset after acceptance'), { name:'TypeError' });
    return reply(fresh ? 202 : 200, { schema:'idleproof.portal-ingest-ack.v1', status:fresh ? 'accepted' : 'duplicate', snapshotId:snapshot.snapshotId });
  };
  return { fetchImpl, stored, bodies };
}

function configuredProject(token = `ipd_${'x'.repeat(32)}`) {
  const cwd = twoChanges();
  writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token });
  return cwd;
}

test('three syncs without a change never produce a conflict or a stuck snapshot', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const results = [];
    for (let i = 0; i < 4; i += 1) results.push(await syncPortal(cwd, { fetchImpl:portal.fetchImpl }));
    assert.deepEqual(results.map((r) => r.ok), [true, true, true, true]);
    assert.equal(results.every((r) => r.pending === 0), true);
    // The unchanged receipt is resent byte-for-byte and stored once.
    assert.equal(portal.bodies.length, 4);
    assert.equal(portal.bodies.every((body) => body === portal.bodies[0]), true);
    assert.equal(portal.stored.size, 1);
  } finally { cleanup(cwd); }
});

test('a lost acknowledgement is retried with the identical body and becomes a duplicate', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator({ loseFirstAck:true });
    const first = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(first.ok, false);
    assert.equal(first.pending, 1);
    const second = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(second.ok, true);
    assert.equal(second.pending, 0);
    assert.equal(portal.bodies[1], portal.bodies[0]);
    assert.equal(portal.stored.size, 1);
  } finally { cleanup(cwd); }
});

test('new content is a new receipt; a rotated credential or a new project gets the same body, never a conflict', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const changed = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(changed.ok, true);
    assert.equal(portal.stored.size, 2);
    // Rotated credential, same Portal project: the stored receipt is recognised as a duplicate.
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'y'.repeat(32)}` });
    const rotated = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(rotated.ok, true);
    assert.equal(portal.stored.size, 2);
    // A different Portal project has never seen it: it is accepted there, with the same body.
    const other = portalEmulator();
    const moved = await syncPortal(cwd, { fetchImpl:other.fetchImpl });
    assert.equal(moved.ok, true);
    assert.equal(other.bodies[0], portal.bodies.at(-1));
  } finally { cleanup(cwd); }
});

test('resending the same measurement of a change adds no receipt; a new measurement does', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const first = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:portal.fetchImpl });
    assert.equal(first.ok, true);
    // Project state evolves (a newer task), then the same measurement is sent again.
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const again = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:portal.fetchImpl });
    assert.equal(again.ok, true);
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(again.snapshotId, first.snapshotId);
    assert.equal(portal.stored.size, 1);
    const remeasured = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 5), { fetchImpl:portal.fetchImpl });
    assert.equal(remeasured.ok, true);
    assert.equal(portal.stored.size, 2);
  } finally { cleanup(cwd); }
});

test('the first saved state excludes .idleproof/ locally, even when a task runs before any identity command', () => {
  const cwd = tmp();
  try {
    execFileSync('git', ['init', '-q'], { cwd });
    saveState(cwd, freshState(cwd));
    assert.match(fs.readFileSync(path.join(cwd, '.git', 'info', 'exclude'), 'utf8'), /^\.idleproof\/$/m);
    assert.equal(execFileSync('git', ['status', '--porcelain'], { cwd, encoding:'utf8' }).trim(), '');
  } finally { cleanup(cwd); }
});

test('the local exclusion also covers a project below the repository root and a worktree', () => {
  const root = tmp();
  try {
    execFileSync('git', ['init', '-q'], { cwd:root });
    execFileSync('git', ['-c', 'user.email=t@e.invalid', '-c', 'user.name=T', 'commit', '-q', '--allow-empty', '-m', 'root'], { cwd:root });
    const nested = path.join(root, 'services', 'api');
    fs.mkdirSync(nested, { recursive:true });
    saveState(nested, freshState(nested));
    assert.equal(execFileSync('git', ['status', '--porcelain', '--untracked-files=all'], { cwd:root, encoding:'utf8' }).trim(), '');
    const worktree = path.join(root, '..', `${path.basename(root)}-wt`);
    execFileSync('git', ['worktree', 'add', '-q', worktree], { cwd:root });
    try {
      saveState(worktree, freshState(worktree));
      assert.equal(execFileSync('git', ['status', '--porcelain', '--untracked-files=all'], { cwd:worktree, encoding:'utf8' }).trim(), '');
    } finally { execFileSync('git', ['worktree', 'remove', '--force', worktree], { cwd:root }); }
  } finally { cleanup(root); }
});

test('a snapshot queued before an upgrade keeps its own time after delivery', async () => {
  const { syncPortal, queuePortalSnapshot, buildCurrentPortalSnapshot } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    // An older client queued the current snapshot without recording its time.
    const old = { ...buildCurrentPortalSnapshot(cwd), generatedAt:'2026-09-01T00:00:00.000Z' };
    fs.writeFileSync(projectPaths(cwd).portalQueue, JSON.stringify([old]));
    const portal = portalEmulator();
    const results = [];
    for (let i = 0; i < 3; i += 1) results.push(await syncPortal(cwd, { fetchImpl:portal.fetchImpl }));
    assert.deepEqual(results.map((r) => r.ok), [true, true, true]);
    assert.equal(portal.bodies.every((body) => JSON.parse(body).generatedAt === '2026-09-01T00:00:00.000Z'), true);
    assert.equal(portal.stored.size, 1);
    void queuePortalSnapshot;
  } finally { cleanup(cwd); }
});

test('a conflict means Portal already holds the receipt: it leaves the queue and does not block later ones', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    // Simulate a pre-fix client state: the time record is lost, so the rebuilt body differs.
    fs.rmSync(projectPaths(cwd).portalSnapshotTimes, { force:true });
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const { queuePortalSnapshot } = await import('../src/portal-client.mjs');
    const stale = JSON.parse(portal.bodies[0]);
    fs.writeFileSync(projectPaths(cwd).portalQueue, JSON.stringify([{ ...stale, generatedAt:'2026-09-02T00:00:00.000Z' }]));
    queuePortalSnapshot(cwd);
    const result = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(result.ok, true);
    assert.equal(result.pending, 0);
    assert.equal(result.heldByPortal, 1);
    assert.equal(portal.stored.size, 2);
  } finally { cleanup(cwd); }
});

test('a measurement resent after enrolling another Portal project reaches that project', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const cwd = configuredProject();
  try {
    const first = portalEmulator();
    await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:first.fetchImpl });
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'z'.repeat(32)}` });
    const second = portalEmulator();
    const again = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:second.fetchImpl });
    assert.equal(again.ok, true);
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(second.stored.size, 1);
    assert.equal(second.bodies[0], first.bodies[0]);
  } finally { cleanup(cwd); }
});

test('a measurement delivered by the IDE hook and resent by the command stays one receipt', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const { queueMatchingDiffWitnessAssurance } = await import('../src/ide-assurance.mjs');
  const { flushPortalQueue } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const envelope = envelopeFor(`dwchg_${'1'.repeat(24)}`, 8);
    const file = path.join(cwd, '.git', 'diffwitness', 'change-envelope.json');
    fs.mkdirSync(path.dirname(file), { recursive:true });
    fs.writeFileSync(file, JSON.stringify(envelope));
    // The hook also schedules a detached background flush; an invalid NODE_OPTIONS makes that
    // child exit at startup so only the emulator below delivers.
    const nodeOptions = process.env.NODE_OPTIONS;
    process.env.NODE_OPTIONS = '--idleproof-test-no-background-flush';
    let hooked;
    try { hooked = queueMatchingDiffWitnessAssurance(cwd); }
    finally { if (nodeOptions === undefined) delete process.env.NODE_OPTIONS; else process.env.NODE_OPTIONS = nodeOptions; }
    assert.equal(hooked.matched, true);
    assert.equal((await flushPortalQueue(cwd, { fetchImpl:portal.fetchImpl })).ok, true);
    // Project state evolves (a newer task), then the user sends the same measurement by command.
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const again = await syncPortalAssurance(cwd, envelope, { fetchImpl:portal.fetchImpl });
    assert.equal(again.ok, true);
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(again.snapshotId, hooked.snapshotId);
    // Portal also holds the hook's ordinary task receipt; the measurement itself is one receipt.
    const receipts = [...portal.stored.values()].map((body) => JSON.parse(body)).filter((snapshot) => snapshot.assurance);
    assert.equal(receipts.length, 1);
  } finally { cleanup(cwd); }
});

test('a damaged local time record is never uploaded; the snapshot keeps a valid time', async () => {
  const { syncPortal, buildCurrentPortalSnapshot } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const snapshotId = buildCurrentPortalSnapshot(cwd).snapshotId;
    fs.mkdirSync(path.dirname(projectPaths(cwd).portalSnapshotTimes), { recursive:true });
    fs.writeFileSync(projectPaths(cwd).portalSnapshotTimes, JSON.stringify({ schema:'idleproof.portal-snapshot-times.v1', entries:[{ snapshotId, generatedAt:'not a time' }] }));
    const portal = portalEmulator();
    const results = [];
    for (let i = 0; i < 2; i += 1) results.push(await syncPortal(cwd, { fetchImpl:portal.fetchImpl }));
    assert.deepEqual(results.map((r) => r.ok), [true, true]);
    const times = portal.bodies.map((body) => JSON.parse(body).generatedAt);
    assert.equal(times.every((value) => /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)), true);
    assert.equal(new Set(times).size, 1);
    assert.equal(portal.stored.size, 1);
  } finally { cleanup(cwd); }
});

const holdAssuranceLock = async (cwd, pid = process.pid) => {
  const { __memoryLockTest } = await import('../src/portal-memory-lock.mjs');
  const lock = projectPaths(cwd).portalAssuranceLock;
  const incarnation = pid === process.pid ? __memoryLockTest.ownIncarnation() : 'U';
  fs.mkdirSync(lock, { recursive:true });
  fs.writeFileSync(path.join(lock, 'owner'), `${pid} ${incarnation} ${'a'.repeat(32)}\n`);
  return lock;
};
const receiptChild = (cwd, points = 8) => {
  const assuranceModule = new URL('../src/portal-assurance.mjs', import.meta.url).href;
  const script = `const m = await import(${JSON.stringify(assuranceModule)});
try { m.queueAssuranceReceipt(process.cwd(), m.buildAssurancePortalSnapshot(process.cwd(), ${JSON.stringify(envelopeFor(`dwchg_${'1'.repeat(24)}`, points))})); }
catch (error) { process.stderr.write(String(error.code)); process.exit(3); }`;
  return spawn(process.execPath, ['--input-type=module', '-e', script], { cwd, stdio:['ignore', 'ignore', 'pipe'] });
};
const exitOf = (proc) => new Promise((resolve) => { let stderr = ''; proc.stderr.on('data', (c) => { stderr += c; }); proc.on('exit', (code) => resolve({ code, stderr })); });

test('recording a receipt waits for another process holding the receipt cache', async () => {
  const cwd = configuredProject();
  try {
    const lock = await holdAssuranceLock(cwd); // this live process is updating the cache
    const exited = exitOf(receiptChild(cwd));
    await new Promise((resolve) => setTimeout(resolve, 1000));
    assert.equal(fs.existsSync(projectPaths(cwd).portalAssuranceSent), false);
    assert.equal(fs.existsSync(projectPaths(cwd).portalQueue), false);
    fs.rmSync(lock, { recursive:true, force:true });
    assert.equal((await exited).code, 0);
    assert.equal(JSON.parse(fs.readFileSync(projectPaths(cwd).portalAssuranceSent, 'utf8')).entries.length, 1);
  } finally { cleanup(cwd); }
});

test('an old receipt-cache lock of a live owner is never evicted; a dead owner\'s lock is recovered', async () => {
  const cwd = configuredProject();
  try {
    const lock = await holdAssuranceLock(cwd);
    const past = new Date(Date.now() - 3600_000);
    fs.utimesSync(lock, past, past);
    fs.utimesSync(path.join(lock, 'owner'), past, past);
    const busy = await exitOf(receiptChild(cwd));
    assert.deepEqual(busy, { code:3, stderr:'IDLEPROOF_PORTAL_ASSURANCE_BUSY' });
    assert.equal(fs.existsSync(projectPaths(cwd).portalAssuranceSent), false);
    fs.rmSync(lock, { recursive:true, force:true });
    const gone = spawn(process.execPath, ['-e', ''], { stdio:'ignore' });
    await new Promise((resolve) => gone.on('exit', resolve));
    await holdAssuranceLock(cwd, gone.pid); // its owner has exited
    assert.equal((await exitOf(receiptChild(cwd))).code, 0);
    assert.equal(JSON.parse(fs.readFileSync(projectPaths(cwd).portalAssuranceSent, 'utf8')).entries.length, 1);
  } finally { cleanup(cwd); }
});

test('the retained assurance receipts are private to the user', { skip:process.platform === 'win32' }, async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const cwd = configuredProject();
  const previous = process.umask(0o022);
  try {
    const portal = portalEmulator();
    assert.equal((await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:portal.fetchImpl })).ok, true);
    assert.equal(fs.statSync(projectPaths(cwd).portalAssuranceSent).mode & 0o777, 0o600);
    assert.deepEqual(fs.readdirSync(path.dirname(projectPaths(cwd).portalAssuranceSent)).filter((name) => name.endsWith('.tmp')), []);
  } finally { process.umask(previous); cleanup(cwd); }
});

test('after a conflict the rejected time is never reused and the held snapshot is not resent', async () => {
  const { syncPortal, buildCurrentPortalSnapshot } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const current = buildCurrentPortalSnapshot(cwd);
    portal.stored.set(current.snapshotId, 'body first delivered with time A');
    // A pre-upgrade queue holds the same content with time B and no local time record exists.
    fs.mkdirSync(projectPaths(cwd).dir, { recursive:true });
    fs.writeFileSync(projectPaths(cwd).portalQueue, JSON.stringify([{ ...current, generatedAt:'2026-09-02T00:00:00.000Z' }]));
    const first = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(first.ok, true);
    assert.equal(first.heldByPortal, 1);
    const sent = portal.bodies.length;
    const later = [await syncPortal(cwd, { fetchImpl:portal.fetchImpl }), await syncPortal(cwd, { fetchImpl:portal.fetchImpl })];
    assert.deepEqual(later.map((r) => [r.ok, r.queueReason, r.delivered]), [[true, 'held-by-portal', 0], [true, 'held-by-portal', 0]]);
    assert.equal(portal.bodies.length, sent);
    const times = fs.existsSync(projectPaths(cwd).portalSnapshotTimes) ? JSON.parse(fs.readFileSync(projectPaths(cwd).portalSnapshotTimes, 'utf8')).entries : [];
    assert.equal(times.some((item) => item.snapshotId === current.snapshotId && item.generatedAt === '2026-09-02T00:00:00.000Z'), false);
  } finally { cleanup(cwd); }
});

test('an earlier change of a reused IDE session keeps its debt after a later turn', async () => {
  const { processHookEvent } = await import('../src/hook.mjs');
  const cwd = tmp();
  try {
    const git = (...args) => execFileSync('git', args, { cwd, encoding:'utf8', stdio:['ignore', 'pipe', 'pipe'] }).trim();
    git('init', '-q'); git('config', 'user.email', 'r@idleproof.local'); git('config', 'user.name', 'R');
    fs.writeFileSync(path.join(cwd, 'app.js'), 'export const value = 1;\n'); git('add', 'app.js'); git('commit', '-qm', 'base');
    const sessionId = 'reused-ide-session';
    const turn = (text, prompt = 'Change the value') => {
      processHookEvent({ cwd, session_id:sessionId, hook_event_name:'UserPromptSubmit', prompt });
      fs.writeFileSync(path.join(cwd, 'app.js'), text);
      processHookEvent({ cwd, session_id:sessionId, hook_event_name:'Stop' });
      return loadState(cwd).sessions[sessionId].proof.changeId;
    };
    const first = turn('export const value = 2;\n', 'First task: set the value to two');
    const firstPrompt = loadState(cwd).sessions[sessionId].promptSha256;
    const second = turn('export const value = 3;\n', 'Second task: set the value to three');
    assert.match(first, /^dwchg_[a-f0-9]{24}$/);
    assert.notEqual(first, second);
    const earlier = buildAssurancePortalSnapshot(cwd, envelopeFor(first, 8));
    assert.equal(earlier.change.changeId, first);
    // The receipt describes the first task, not the later turn of the same session.
    assert.ok(JSON.stringify(earlier).includes(`sha256:${firstPrompt}`));
    assert.ok(!JSON.stringify(earlier).includes(`sha256:${loadState(cwd).sessions[sessionId].promptSha256}`));
    assert.deepEqual(earlier.assurance.softwareDebt, { points:8, obligations:2, budgetPassed:true });
    assert.equal(buildAssurancePortalSnapshot(cwd, envelopeFor(second, 3)).change.changeId, second);
    assert.throws(() => buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'9'.repeat(24)}`, 1)), /matches no change completed by IdleProof/);
    // A third turn starts: the live session now carries its prompt while proof still names change 2.
    const secondPrompt = loadState(cwd).sessions[sessionId].promptSha256;
    processHookEvent({ cwd, session_id:sessionId, hook_event_name:'UserPromptSubmit', prompt:'Third task, still running' });
    const during = JSON.stringify(buildAssurancePortalSnapshot(cwd, envelopeFor(second, 3)));
    assert.ok(during.includes(`sha256:${secondPrompt}`));
    assert.ok(!during.includes(`sha256:${loadState(cwd).sessions[sessionId].promptSha256}`));
  } finally { cleanup(cwd); }
});

test('a receipt Portal already holds is retained again when the local cache was lost', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const { createHash } = await import('node:crypto');
  const token = `ipd_${'x'.repeat(32)}`;
  const cwd = configuredProject(token);
  try {
    const portal = portalEmulator();
    const envelope = envelopeFor(`dwchg_${'1'.repeat(24)}`, 8);
    const first = await syncPortalAssurance(cwd, envelope, { fetchImpl:portal.fetchImpl });
    assert.equal(first.ok, true);
    // The receipt cache is lost while this destination is known to hold the receipt.
    fs.rmSync(projectPaths(cwd).portalAssuranceSent);
    const destination = createHash('sha256').update(`http://127.0.0.1:8787/api/v1/snapshots\n${token}`).digest('hex').slice(0, 32);
    fs.writeFileSync(projectPaths(cwd).portalHeld, JSON.stringify({ schema:'idleproof.portal-held.v1', entries:[{ destination, snapshotId:first.snapshotId }] }));
    const held = await syncPortalAssurance(cwd, envelope, { fetchImpl:portal.fetchImpl });
    assert.equal(held.queueReason, 'held-by-portal');
    // The receipt is retained again, so a later resend reuses it instead of rebuilding a new one.
    const sent = JSON.parse(fs.readFileSync(projectPaths(cwd).portalAssuranceSent, 'utf8')).entries;
    assert.deepEqual(sent.map((item) => item.snapshot.snapshotId), [first.snapshotId]);
    const again = await syncPortalAssurance(cwd, envelope, { fetchImpl:portal.fetchImpl });
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(again.snapshotId, first.snapshotId);
  } finally { cleanup(cwd); }
});

test('a measurement whose receipt body was evicted is never sent again as a second receipt', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const change = `dwchg_${'1'.repeat(24)}`;
    const first = await syncPortalAssurance(cwd, envelopeFor(change, 1), { fetchImpl:portal.fetchImpl });
    for (let points = 2; points <= 70; points += 1) await syncPortalAssurance(cwd, envelopeFor(change, points), { fetchImpl:portal.fetchImpl });
    const entries = JSON.parse(fs.readFileSync(projectPaths(cwd).portalAssuranceSent, 'utf8')).entries;
    assert.equal(entries.length, 70);
    assert.equal(entries.filter((item) => item.snapshot).length, 64);
    assert.equal(entries[0].snapshot, undefined);
    assert.equal(entries[0].snapshotId, first.snapshotId);
    const posts = portal.bodies.length;
    const again = await syncPortalAssurance(cwd, envelopeFor(change, 1), { fetchImpl:portal.fetchImpl });
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(again.snapshotId, first.snapshotId);
    assert.equal(portal.bodies.length, posts);
    // A newly enrolled destination never got it: an explicit refusal, not a silent success.
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'n'.repeat(32)}` });
    const elsewhere = await syncPortalAssurance(cwd, envelopeFor(change, 1), { fetchImpl:portal.fetchImpl });
    assert.deepEqual([elsewhere.ok, elsewhere.errorCode, elsewhere.queueReason], [false, 'IDLEPROOF_ASSURANCE_NOT_RETAINED', 'not-retained']);
    assert.equal(portal.bodies.length, posts);
  } finally { cleanup(cwd); }
});

test('configure never reports success when another configure replaced its credential', async () => {
  const { configurePortal, readPortalConfig } = await import('../src/portal-client.mjs');
  const cwd = tmp();
  const realRename = fs.renameSync;
  const endpoint = 'http://127.0.0.1:8787/api/v1/snapshots';
  const mine = `ipd_${'m'.repeat(32)}`;
  let raced = 0;
  try {
    // A concurrent configure for the same endpoint writes another project's credential right after ours.
    fs.renameSync = (from, to, ...args) => {
      const result = realRename(from, to, ...args);
      if (raced === 0 && to === projectPaths(cwd).portalConfig) {
        raced += 1;
        fs.writeFileSync(to, JSON.stringify({ schema:'idleproof.portal-config.v1', enabled:true, endpoint, token:`ipd_${'o'.repeat(32)}`, updatedAt:new Date().toISOString() }));
      }
      return result;
    };
    const status = configurePortal(cwd, { endpoint, token:mine });
    fs.renameSync = realRename;
    assert.equal(raced, 1);
    assert.equal(status.tokenLast4, mine.slice(-4));
    assert.equal(readPortalConfig(cwd).token, mine);
  } finally { fs.renameSync = realRename; cleanup(cwd); }
});
