import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { freshState, loadState, saveState } from '../src/state.mjs';
import { ensurePortalIdentity, portalStatus, writePortalConfig } from '../src/portal-client.mjs';
import { buildAssurancePortalSnapshot } from '../src/portal-assurance.mjs';
import { projectPaths } from '../src/paths.mjs';

const CLI = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'idleproof.mjs');
const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'idleproof-first-project-'));
const cleanup = (cwd) => { try { fs.rmSync(cwd, { recursive:true, force:true }); } catch {} };
const cli = (cwd, ...args) => execFileSync(process.execPath, [CLI, ...args], { cwd, encoding:'utf8' }).trim();

test('the enrollment identity is stable before any task, across processes, and creates no task', () => {
  const cwd = tmp();
  try {
    execFileSync('git', ['init', '-q'], { cwd });
    const first = cli(cwd, 'portal', 'identity');
    const second = cli(cwd, 'portal', 'identity');
    const json = JSON.parse(cli(cwd, 'portal', 'identity', '--json'));
    assert.match(first, /^[a-f0-9]{24}$/);
    assert.equal(second, first);
    assert.equal(json.projectLocalId, first);
    // Persisted state carries the identity; no session/task was fabricated to obtain it.
    assert.equal(fs.existsSync(projectPaths(cwd).state), true);
    assert.deepEqual(Object.keys(loadState(cwd).sessions), []);
    assert.equal(portalStatus(cwd).projectLocalId, first);
    // The local state directory is excluded from Git locally (not a tracked .gitignore edit).
    assert.match(fs.readFileSync(path.join(cwd, '.git', 'info', 'exclude'), 'utf8'), /^\.idleproof\/$/m);
    assert.equal(fs.existsSync(path.join(cwd, '.gitignore')), false);
    ensurePortalIdentity(cwd);
    assert.equal(fs.readFileSync(path.join(cwd, '.git', 'info', 'exclude'), 'utf8').match(/^\.idleproof\/$/gm).length, 1);
  } finally { cleanup(cwd); }
});

test('an existing persisted identity is kept, never regenerated by identity or configure', () => {
  const cwd = tmp();
  try {
    const state = freshState(cwd);
    state.createdAt = '2026-01-02T03:04:05.000Z';
    saveState(cwd, state);
    const before = portalStatus(cwd).projectLocalId;
    assert.equal(portalStatus(cwd).identityPersisted, true);
    assert.equal(ensurePortalIdentity(cwd).projectLocalId, before);
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'x'.repeat(32)}` });
    assert.equal(portalStatus(cwd).projectLocalId, before);
    assert.equal(loadState(cwd).createdAt, '2026-01-02T03:04:05.000Z');
  } finally { cleanup(cwd); }
});

test('status reports an uninitialized identity instead of a value that would change', () => {
  const cwd = tmp();
  try {
    const status = portalStatus(cwd);
    assert.equal(status.identityPersisted, false);
    assert.match(cli(cwd, 'portal', 'status'), /identity not initialized yet/);
    assert.equal(fs.existsSync(projectPaths(cwd).state), false);
  } finally { cleanup(cwd); }
});

function twoChanges() {
  const cwd = tmp();
  const state = freshState(cwd);
  const session = (id, changeId, at) => ({
    id, source:'run', status:'complete', startedAt:at, lastEventAt:at, completedAt:at, promptChars:0,
    touchedFiles:['app.py'], changed:{ added:1, deleted:0 }, concepts:{}, events:[],
    proof:{ changeId, diffSha256:'c'.repeat(64) }, taskSignals:{ file:'app.py' }
  });
  state.sessions.first = session('first', `dwchg_${'1'.repeat(24)}`, '2026-09-26T10:00:00.000Z');
  state.sessions.second = session('second', `dwchg_${'2'.repeat(24)}`, '2026-09-26T11:00:00.000Z');
  saveState(cwd, state);
  return cwd;
}
const envelopeFor = (changeId, points) => ({
  schema_version:'change-envelope-1', change_id:changeId,
  privacy:{ code_uploaded:false, contains_paths:false, contains_prompt_text:false },
  debt:{ report_schema:'debt-report-1', points, open_lineages:['DW-0123456789AB', 'DW-0123456789AC'], budget_passed:true }
});

test('debt of an earlier change stays attached to that change after a newer task', () => {
  const cwd = twoChanges();
  try {
    const first = buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8));
    assert.equal(first.change.changeId, `dwchg_${'1'.repeat(24)}`);
    assert.deepEqual(first.assurance.softwareDebt, { points:8, obligations:2, budgetPassed:true });
    const second = buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'2'.repeat(24)}`, 3));
    assert.equal(second.change.changeId, `dwchg_${'2'.repeat(24)}`);
    assert.notEqual(second.snapshotId, first.snapshotId);
  } finally { cleanup(cwd); }
});

test('a measurement of a change IdleProof did not complete is refused, not attached to the latest task', () => {
  const cwd = twoChanges();
  try {
    assert.throws(() => buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'3'.repeat(24)}`, 8)), /matches no change completed by IdleProof/);
    assert.equal(fs.existsSync(projectPaths(cwd).portalQueue), false);
  } finally { cleanup(cwd); }
});

// A Portal emulator with the real retransmission rule: same id + same body → duplicate,
// same id + different body → 409 SNAPSHOT_CONFLICT.
function portalEmulator({ loseFirstAck = false } = {}) {
  const stored = new Map();
  const bodies = [];
  let calls = 0;
  const fetchImpl = async (_url, { body }) => {
    calls += 1;
    bodies.push(body);
    const snapshot = JSON.parse(body);
    const known = stored.get(snapshot.snapshotId);
    const reply = (status, value) => ({ status, text: async () => JSON.stringify(value) });
    if (known !== undefined && known !== body) return reply(409, { error:{ code:'SNAPSHOT_CONFLICT' } });
    const fresh = known === undefined;
    stored.set(snapshot.snapshotId, body);
    if (loseFirstAck && calls === 1) throw Object.assign(new Error('connection reset after acceptance'), { name:'TypeError' });
    return reply(fresh ? 202 : 200, { schema:'idleproof.portal-ingest-ack.v1', status:fresh ? 'accepted' : 'duplicate', snapshotId:snapshot.snapshotId });
  };
  return { fetchImpl, stored, bodies };
}

function configuredProject(token = `ipd_${'x'.repeat(32)}`) {
  const cwd = twoChanges();
  writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token });
  return cwd;
}

test('three syncs without a change never produce a conflict or a stuck snapshot', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const results = [];
    for (let i = 0; i < 4; i += 1) results.push(await syncPortal(cwd, { fetchImpl:portal.fetchImpl }));
    assert.deepEqual(results.map((r) => r.ok), [true, true, true, true]);
    assert.equal(results.every((r) => r.pending === 0), true);
    // The unchanged receipt is resent byte-for-byte and stored once.
    assert.equal(portal.bodies.length, 4);
    assert.equal(portal.bodies.every((body) => body === portal.bodies[0]), true);
    assert.equal(portal.stored.size, 1);
  } finally { cleanup(cwd); }
});

test('a lost acknowledgement is retried with the identical body and becomes a duplicate', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator({ loseFirstAck:true });
    const first = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(first.ok, false);
    assert.equal(first.pending, 1);
    const second = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(second.ok, true);
    assert.equal(second.pending, 0);
    assert.equal(portal.bodies[1], portal.bodies[0]);
    assert.equal(portal.stored.size, 1);
  } finally { cleanup(cwd); }
});

test('new content is a new receipt; a rotated credential or a new project gets the same body, never a conflict', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const changed = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(changed.ok, true);
    assert.equal(portal.stored.size, 2);
    // Rotated credential, same Portal project: the stored receipt is recognised as a duplicate.
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'y'.repeat(32)}` });
    const rotated = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(rotated.ok, true);
    assert.equal(portal.stored.size, 2);
    // A different Portal project has never seen it: it is accepted there, with the same body.
    const other = portalEmulator();
    const moved = await syncPortal(cwd, { fetchImpl:other.fetchImpl });
    assert.equal(moved.ok, true);
    assert.equal(other.bodies[0], portal.bodies.at(-1));
  } finally { cleanup(cwd); }
});

test('resending the same measurement of a change adds no receipt; a new measurement does', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const first = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:portal.fetchImpl });
    assert.equal(first.ok, true);
    // Project state evolves (a newer task), then the same measurement is sent again.
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const again = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:portal.fetchImpl });
    assert.equal(again.ok, true);
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(again.snapshotId, first.snapshotId);
    assert.equal(portal.stored.size, 1);
    const remeasured = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 5), { fetchImpl:portal.fetchImpl });
    assert.equal(remeasured.ok, true);
    assert.equal(portal.stored.size, 2);
  } finally { cleanup(cwd); }
});
