import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { freshState, loadState, saveState } from '../src/state.mjs';
import { ensurePortalIdentity, portalStatus, writePortalConfig } from '../src/portal-client.mjs';
import { buildAssurancePortalSnapshot } from '../src/portal-assurance.mjs';
import { projectPaths } from '../src/paths.mjs';

const CLI = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'idleproof.mjs');
const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'idleproof-first-project-'));
const cleanup = (cwd) => { try { fs.rmSync(cwd, { recursive:true, force:true }); } catch {} };
const cli = (cwd, ...args) => execFileSync(process.execPath, [CLI, ...args], { cwd, encoding:'utf8' }).trim();

test('the enrollment identity is stable before any task, across processes, and creates no task', () => {
  const cwd = tmp();
  try {
    execFileSync('git', ['init', '-q'], { cwd });
    const first = cli(cwd, 'portal', 'identity');
    const second = cli(cwd, 'portal', 'identity');
    const json = JSON.parse(cli(cwd, 'portal', 'identity', '--json'));
    assert.match(first, /^[a-f0-9]{24}$/);
    assert.equal(second, first);
    assert.equal(json.projectLocalId, first);
    // Persisted state carries the identity; no session/task was fabricated to obtain it.
    assert.equal(fs.existsSync(projectPaths(cwd).state), true);
    assert.deepEqual(Object.keys(loadState(cwd).sessions), []);
    assert.equal(portalStatus(cwd).projectLocalId, first);
    // The local state directory is excluded from Git locally (not a tracked .gitignore edit).
    assert.match(fs.readFileSync(path.join(cwd, '.git', 'info', 'exclude'), 'utf8'), /^\.idleproof\/$/m);
    assert.equal(fs.existsSync(path.join(cwd, '.gitignore')), false);
    ensurePortalIdentity(cwd);
    assert.equal(fs.readFileSync(path.join(cwd, '.git', 'info', 'exclude'), 'utf8').match(/^\.idleproof\/$/gm).length, 1);
  } finally { cleanup(cwd); }
});

test('an existing persisted identity is kept, never regenerated by identity or configure', () => {
  const cwd = tmp();
  try {
    const state = freshState(cwd);
    state.createdAt = '2026-01-02T03:04:05.000Z';
    saveState(cwd, state);
    const before = portalStatus(cwd).projectLocalId;
    assert.equal(portalStatus(cwd).identityPersisted, true);
    assert.equal(ensurePortalIdentity(cwd).projectLocalId, before);
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'x'.repeat(32)}` });
    assert.equal(portalStatus(cwd).projectLocalId, before);
    assert.equal(loadState(cwd).createdAt, '2026-01-02T03:04:05.000Z');
  } finally { cleanup(cwd); }
});

test('status reports an uninitialized identity instead of a value that would change', () => {
  const cwd = tmp();
  try {
    const status = portalStatus(cwd);
    assert.equal(status.identityPersisted, false);
    assert.match(cli(cwd, 'portal', 'status'), /identity not initialized yet/);
    assert.equal(fs.existsSync(projectPaths(cwd).state), false);
  } finally { cleanup(cwd); }
});

function twoChanges() {
  const cwd = tmp();
  const state = freshState(cwd);
  const session = (id, changeId, at) => ({
    id, source:'run', status:'complete', startedAt:at, lastEventAt:at, completedAt:at, promptChars:0,
    touchedFiles:['app.py'], changed:{ added:1, deleted:0 }, concepts:{}, events:[],
    proof:{ changeId, diffSha256:'c'.repeat(64) }, taskSignals:{ file:'app.py' }
  });
  state.sessions.first = session('first', `dwchg_${'1'.repeat(24)}`, '2026-09-26T10:00:00.000Z');
  state.sessions.second = session('second', `dwchg_${'2'.repeat(24)}`, '2026-09-26T11:00:00.000Z');
  saveState(cwd, state);
  return cwd;
}
const envelopeFor = (changeId, points) => ({
  schema_version:'change-envelope-1', change_id:changeId,
  privacy:{ code_uploaded:false, contains_paths:false, contains_prompt_text:false },
  debt:{ report_schema:'debt-report-1', points, open_lineages:['DW-0123456789AB', 'DW-0123456789AC'], budget_passed:true }
});

test('debt of an earlier change stays attached to that change after a newer task', () => {
  const cwd = twoChanges();
  try {
    const first = buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8));
    assert.equal(first.change.changeId, `dwchg_${'1'.repeat(24)}`);
    assert.deepEqual(first.assurance.softwareDebt, { points:8, obligations:2, budgetPassed:true });
    const second = buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'2'.repeat(24)}`, 3));
    assert.equal(second.change.changeId, `dwchg_${'2'.repeat(24)}`);
    assert.notEqual(second.snapshotId, first.snapshotId);
  } finally { cleanup(cwd); }
});

test('a measurement of a change IdleProof did not complete is refused, not attached to the latest task', () => {
  const cwd = twoChanges();
  try {
    assert.throws(() => buildAssurancePortalSnapshot(cwd, envelopeFor(`dwchg_${'3'.repeat(24)}`, 8)), /matches no change completed by IdleProof/);
    assert.equal(fs.existsSync(projectPaths(cwd).portalQueue), false);
  } finally { cleanup(cwd); }
});

// A Portal emulator with the real retransmission rule: same id + same body → duplicate,
// same id + different body → 409 SNAPSHOT_CONFLICT.
function portalEmulator({ loseFirstAck = false } = {}) {
  const stored = new Map();
  const bodies = [];
  let calls = 0;
  const fetchImpl = async (_url, { body }) => {
    calls += 1;
    bodies.push(body);
    const snapshot = JSON.parse(body);
    const known = stored.get(snapshot.snapshotId);
    const reply = (status, value) => ({ status, text: async () => JSON.stringify(value) });
    if (known !== undefined && known !== body) return reply(409, { error:{ code:'SNAPSHOT_CONFLICT' } });
    const fresh = known === undefined;
    stored.set(snapshot.snapshotId, body);
    if (loseFirstAck && calls === 1) throw Object.assign(new Error('connection reset after acceptance'), { name:'TypeError' });
    return reply(fresh ? 202 : 200, { schema:'idleproof.portal-ingest-ack.v1', status:fresh ? 'accepted' : 'duplicate', snapshotId:snapshot.snapshotId });
  };
  return { fetchImpl, stored, bodies };
}

function configuredProject(token = `ipd_${'x'.repeat(32)}`) {
  const cwd = twoChanges();
  writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token });
  return cwd;
}

test('three syncs without a change never produce a conflict or a stuck snapshot', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const results = [];
    for (let i = 0; i < 4; i += 1) results.push(await syncPortal(cwd, { fetchImpl:portal.fetchImpl }));
    assert.deepEqual(results.map((r) => r.ok), [true, true, true, true]);
    assert.equal(results.every((r) => r.pending === 0), true);
    // The unchanged receipt is resent byte-for-byte and stored once.
    assert.equal(portal.bodies.length, 4);
    assert.equal(portal.bodies.every((body) => body === portal.bodies[0]), true);
    assert.equal(portal.stored.size, 1);
  } finally { cleanup(cwd); }
});

test('a lost acknowledgement is retried with the identical body and becomes a duplicate', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator({ loseFirstAck:true });
    const first = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(first.ok, false);
    assert.equal(first.pending, 1);
    const second = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(second.ok, true);
    assert.equal(second.pending, 0);
    assert.equal(portal.bodies[1], portal.bodies[0]);
    assert.equal(portal.stored.size, 1);
  } finally { cleanup(cwd); }
});

test('new content is a new receipt; a rotated credential or a new project gets the same body, never a conflict', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const changed = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(changed.ok, true);
    assert.equal(portal.stored.size, 2);
    // Rotated credential, same Portal project: the stored receipt is recognised as a duplicate.
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'y'.repeat(32)}` });
    const rotated = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(rotated.ok, true);
    assert.equal(portal.stored.size, 2);
    // A different Portal project has never seen it: it is accepted there, with the same body.
    const other = portalEmulator();
    const moved = await syncPortal(cwd, { fetchImpl:other.fetchImpl });
    assert.equal(moved.ok, true);
    assert.equal(other.bodies[0], portal.bodies.at(-1));
  } finally { cleanup(cwd); }
});

test('resending the same measurement of a change adds no receipt; a new measurement does', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const first = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:portal.fetchImpl });
    assert.equal(first.ok, true);
    // Project state evolves (a newer task), then the same measurement is sent again.
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const again = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:portal.fetchImpl });
    assert.equal(again.ok, true);
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(again.snapshotId, first.snapshotId);
    assert.equal(portal.stored.size, 1);
    const remeasured = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 5), { fetchImpl:portal.fetchImpl });
    assert.equal(remeasured.ok, true);
    assert.equal(portal.stored.size, 2);
  } finally { cleanup(cwd); }
});

test('the first saved state excludes .idleproof/ locally, even when a task runs before any identity command', () => {
  const cwd = tmp();
  try {
    execFileSync('git', ['init', '-q'], { cwd });
    saveState(cwd, freshState(cwd));
    assert.match(fs.readFileSync(path.join(cwd, '.git', 'info', 'exclude'), 'utf8'), /^\.idleproof\/$/m);
    assert.equal(execFileSync('git', ['status', '--porcelain'], { cwd, encoding:'utf8' }).trim(), '');
  } finally { cleanup(cwd); }
});

test('the local exclusion also covers a project below the repository root and a worktree', () => {
  const root = tmp();
  try {
    execFileSync('git', ['init', '-q'], { cwd:root });
    execFileSync('git', ['-c', 'user.email=t@e.invalid', '-c', 'user.name=T', 'commit', '-q', '--allow-empty', '-m', 'root'], { cwd:root });
    const nested = path.join(root, 'services', 'api');
    fs.mkdirSync(nested, { recursive:true });
    saveState(nested, freshState(nested));
    assert.equal(execFileSync('git', ['status', '--porcelain', '--untracked-files=all'], { cwd:root, encoding:'utf8' }).trim(), '');
    const worktree = path.join(root, '..', `${path.basename(root)}-wt`);
    execFileSync('git', ['worktree', 'add', '-q', worktree], { cwd:root });
    try {
      saveState(worktree, freshState(worktree));
      assert.equal(execFileSync('git', ['status', '--porcelain', '--untracked-files=all'], { cwd:worktree, encoding:'utf8' }).trim(), '');
    } finally { execFileSync('git', ['worktree', 'remove', '--force', worktree], { cwd:root }); }
  } finally { cleanup(root); }
});

test('a snapshot queued before an upgrade keeps its own time after delivery', async () => {
  const { syncPortal, queuePortalSnapshot, buildCurrentPortalSnapshot } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    // An older client queued the current snapshot without recording its time.
    const old = { ...buildCurrentPortalSnapshot(cwd), generatedAt:'2026-09-01T00:00:00.000Z' };
    fs.writeFileSync(projectPaths(cwd).portalQueue, JSON.stringify([old]));
    const portal = portalEmulator();
    const results = [];
    for (let i = 0; i < 3; i += 1) results.push(await syncPortal(cwd, { fetchImpl:portal.fetchImpl }));
    assert.deepEqual(results.map((r) => r.ok), [true, true, true]);
    assert.equal(portal.bodies.every((body) => JSON.parse(body).generatedAt === '2026-09-01T00:00:00.000Z'), true);
    assert.equal(portal.stored.size, 1);
    void queuePortalSnapshot;
  } finally { cleanup(cwd); }
});

test('a conflict means Portal already holds the receipt: it leaves the queue and does not block later ones', async () => {
  const { syncPortal } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    // Simulate a pre-fix client state: the time record is lost, so the rebuilt body differs.
    fs.rmSync(projectPaths(cwd).portalSnapshotTimes, { force:true });
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const { queuePortalSnapshot } = await import('../src/portal-client.mjs');
    const stale = JSON.parse(portal.bodies[0]);
    fs.writeFileSync(projectPaths(cwd).portalQueue, JSON.stringify([{ ...stale, generatedAt:'2026-09-02T00:00:00.000Z' }]));
    queuePortalSnapshot(cwd);
    const result = await syncPortal(cwd, { fetchImpl:portal.fetchImpl });
    assert.equal(result.ok, true);
    assert.equal(result.pending, 0);
    assert.equal(result.heldByPortal, 1);
    assert.equal(portal.stored.size, 2);
  } finally { cleanup(cwd); }
});

test('a measurement resent after enrolling another Portal project reaches that project', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const cwd = configuredProject();
  try {
    const first = portalEmulator();
    await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:first.fetchImpl });
    writePortalConfig(cwd, { endpoint:'http://127.0.0.1:8787/api/v1/snapshots', token:`ipd_${'z'.repeat(32)}` });
    const second = portalEmulator();
    const again = await syncPortalAssurance(cwd, envelopeFor(`dwchg_${'1'.repeat(24)}`, 8), { fetchImpl:second.fetchImpl });
    assert.equal(again.ok, true);
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(second.stored.size, 1);
    assert.equal(second.bodies[0], first.bodies[0]);
  } finally { cleanup(cwd); }
});

test('a measurement delivered by the IDE hook and resent by the command stays one receipt', async () => {
  const { syncPortalAssurance } = await import('../src/portal-assurance.mjs');
  const { queueMatchingDiffWitnessAssurance } = await import('../src/ide-assurance.mjs');
  const { flushPortalQueue } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const portal = portalEmulator();
    const envelope = envelopeFor(`dwchg_${'1'.repeat(24)}`, 8);
    const file = path.join(cwd, '.git', 'diffwitness', 'change-envelope.json');
    fs.mkdirSync(path.dirname(file), { recursive:true });
    fs.writeFileSync(file, JSON.stringify(envelope));
    // The hook also schedules a detached background flush; an invalid NODE_OPTIONS makes that
    // child exit at startup so only the emulator below delivers.
    const nodeOptions = process.env.NODE_OPTIONS;
    process.env.NODE_OPTIONS = '--idleproof-test-no-background-flush';
    let hooked;
    try { hooked = queueMatchingDiffWitnessAssurance(cwd); }
    finally { if (nodeOptions === undefined) delete process.env.NODE_OPTIONS; else process.env.NODE_OPTIONS = nodeOptions; }
    assert.equal(hooked.matched, true);
    assert.equal((await flushPortalQueue(cwd, { fetchImpl:portal.fetchImpl })).ok, true);
    // Project state evolves (a newer task), then the user sends the same measurement by command.
    const state = loadState(cwd);
    state.sessions.third = { ...state.sessions.second, id:'third', lastEventAt:'2026-09-26T12:00:00.000Z', proof:{ changeId:`dwchg_${'4'.repeat(24)}`, diffSha256:'d'.repeat(64) } };
    saveState(cwd, state);
    const again = await syncPortalAssurance(cwd, envelope, { fetchImpl:portal.fetchImpl });
    assert.equal(again.ok, true);
    assert.equal(again.queueReason, 'already-sent');
    assert.equal(again.snapshotId, hooked.snapshotId);
    // Portal also holds the hook's ordinary task receipt; the measurement itself is one receipt.
    const receipts = [...portal.stored.values()].map((body) => JSON.parse(body)).filter((snapshot) => snapshot.assurance);
    assert.equal(receipts.length, 1);
  } finally { cleanup(cwd); }
});

test('a damaged local time record is never uploaded; the snapshot keeps a valid time', async () => {
  const { syncPortal, buildCurrentPortalSnapshot } = await import('../src/portal-client.mjs');
  const cwd = configuredProject();
  try {
    const snapshotId = buildCurrentPortalSnapshot(cwd).snapshotId;
    fs.mkdirSync(path.dirname(projectPaths(cwd).portalSnapshotTimes), { recursive:true });
    fs.writeFileSync(projectPaths(cwd).portalSnapshotTimes, JSON.stringify({ schema:'idleproof.portal-snapshot-times.v1', entries:[{ snapshotId, generatedAt:'not a time' }] }));
    const portal = portalEmulator();
    const results = [];
    for (let i = 0; i < 2; i += 1) results.push(await syncPortal(cwd, { fetchImpl:portal.fetchImpl }));
    assert.deepEqual(results.map((r) => r.ok), [true, true]);
    const times = portal.bodies.map((body) => JSON.parse(body).generatedAt);
    assert.equal(times.every((value) => /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)), true);
    assert.equal(new Set(times).size, 1);
    assert.equal(portal.stored.size, 1);
  } finally { cleanup(cwd); }
});
