import assert from 'node:assert/strict';
import { buildLearningExperience } from '../src/learning.mjs';
import { presentLearningCard } from '../src/presentation.mjs';

function sessionFor(item) {
  const phase = item.phase || 'implement';
  const status = phase === 'handoff' ? 'complete' : 'active';
  const capabilities = phase === 'verify'
    ? ['test.execute']
    : phase === 'implement'
      ? [item.capability || 'code.modify']
      : [];
  return {
    id:`bench-${item.id}`,
    source:'claude',
    prompt:item.prompt,
    status,
    currentTool:phase === 'verify' ? 'Bash' : 'Edit',
    currentCapabilities:capabilities,
    touchedFiles:[item.file],
    concepts:{ [item.id]:{ events:3 } },
    taskSignals:item.signals || {},
    estimatedWindow:item.seconds || 24,
    lastEventAt:'2026-08-21T00:00:00.000Z'
  };
}

function stateFor(id) {
  return { ledger:{ [id]:{ confidence:0.15, exposures:2, correct:0, wrong:0 } } };
}

const cases = [
  {
    id:'auth', phase:'verify', file:'src/auth/admin.ts',
    prompt:'Protect the admin export after OAuth login',
    signals:{ symbol:'authorizeAdmin', route:'/api/admin/export', technologies:['OAuth'] },
    expect:[/authorizeAdmin|admin\/export/i, /authentication|authorization|role/i]
  },
  {
    id:'sql', phase:'implement', file:'src/db/orders.ts',
    prompt:'Persist a checkout order with user supplied fields',
    signals:{ symbol:'createOrder', table:'orders', technologies:['PostgreSQL'] },
    expect:[/createOrder|orders\.ts/i, /parameterized|user-controlled|SQL/i]
  },
  {
    id:'migration', phase:'handoff', file:'migrations/20260821_subscriptions.sql',
    prompt:'Add subscription status during a rolling deploy',
    signals:{ table:'subscriptions', technologies:['PostgreSQL'] },
    expect:[/subscriptions/i, /deploy|rollback|halfway/i]
  },
  {
    id:'async', phase:'verify', file:'src/jobs/process-queue.ts',
    prompt:'Make queue processing resilient when two jobs overlap',
    signals:{ symbol:'processQueue', technologies:['Node.js'] },
    expect:[/processQueue/i, /overlap|failing|inconsistent|race/i]
  },
  {
    id:'react-state', phase:'implement', file:'src/components/CheckoutForm.tsx',
    prompt:'Synchronize checkout form state with an external payment widget',
    signals:{ symbol:'CheckoutForm', technologies:['React'] },
    expect:[/CheckoutForm/i, /effect|external system|state/i]
  },
  {
    id:'typescript', phase:'verify', file:'src/webhooks/parse.ts',
    prompt:'Type the webhook payload returned by an external provider',
    signals:{ symbol:'parseWebhook', technologies:['TypeScript'] },
    expect:[/parseWebhook/i, /malformed|runtime|external boundary|TypeScript/i]
  },
  {
    id:'testing', phase:'verify', file:'src/pricing/calculate.ts',
    prompt:'Add regression evidence for checkout totals',
    signals:{ symbol:'calculateTotal' },
    expect:[/calculateTotal/i, /plausible wrong implementation|convincing|regress/i]
  },
  {
    id:'secrets', phase:'implement', file:'src/stripe/client.ts',
    prompt:'Configure the Stripe server client',
    signals:{ symbol:'stripeClient', technologies:['Stripe'] },
    expect:[/Stripe credential|stripeClient/i, /secret safely|credential/i]
  },
  {
    id:'http', phase:'implement', file:'src/api/stripe-webhook.ts',
    prompt:'Handle Stripe retries without processing the same event twice',
    signals:{ symbol:'handleStripeWebhook', route:'/api/webhooks/stripe', technologies:['Stripe'] },
    expect:[/webhooks\/stripe/i, /idempot|property|retries/i]
  },
  {
    id:'packages', phase:'implement', capability:'dependency.install', file:'package.json',
    prompt:'Add a schema validation dependency',
    signals:{ technologies:['Node.js'] },
    expect:[/package\.json/i, /dependency|repo|platform|package/i]
  },
  {
    id:'git', phase:'handoff', file:'src/profile/update.ts',
    prompt:'Finish a profile update patch generated by the agent',
    signals:{ symbol:'updateProfile' },
    expect:[/updateProfile/i, /scope|unrelated|review|revert|change boundary/i]
  },
  {
    id:'ci', phase:'implement', capability:'ci.modify', file:'.github/workflows/deploy.yml',
    prompt:'Allow the deploy workflow to publish a release',
    signals:{ technologies:['GitHub Actions'] },
    expect:[/deploy\.yml/i, /least privilege|credential|workflow/i]
  },
  {
    id:'concurrency', phase:'verify', file:'src/booking/reserve.ts',
    prompt:'Prevent two buyers from reserving the same seat',
    signals:{ symbol:'reserveSeat', table:'reservations' },
    expect:[/reserveSeat/i, /concurrent|state transition|race|shared/i]
  },
  {
    id:'accessibility', phase:'implement', file:'src/components/CheckoutButton.tsx',
    prompt:'Make the custom checkout control keyboard accessible',
    signals:{ symbol:'CheckoutButton', technologies:['React'] },
    expect:[/CheckoutButton/i, /native semantic|interactive control|semantic element/i]
  },
  {
    id:'cache', phase:'verify', file:'src/profile/cache.ts',
    prompt:'Cache profile reads without serving stale updates',
    signals:{ symbol:'getProfile', technologies:['Redis'] },
    expect:[/getProfile/i, /fresh|source of truth|cache/i]
  }
];

let passed = 0;
for (const item of cases) {
  const session = sessionFor(item);
  const experience = buildLearningExperience(stateFor(item.id), session, item.id);
  assert.equal(experience.selectedConceptId, item.id, `${item.id}: wrong concept selected`);
  const card = presentLearningCard(experience.card, session);
  assert.ok(card, `${item.id}: no card`);
  assert.equal(card.answer, 0, `${item.id}: applied benchmark assumes the curated correct answer remains index 0`);
  assert.equal(card.options.length, 3, `${item.id}: expected one-tap 3-option interaction`);
  assert.ok(card.question.length <= 240, `${item.id}: question too long (${card.question.length})`);
  assert.ok(card.context?.task, `${item.id}: task grounding disappeared`);
  assert.equal(card.context?.file, item.file, `${item.id}: file grounding disappeared`);
  for (const pattern of item.expect) assert.match(card.question, pattern, `${item.id}: question missed ${pattern} -> ${card.question}`);
  assert.doesNotMatch(card.question, /font weight|source-map size|README logo/i, `${item.id}: distractor leaked into the question itself`);
  passed += 1;
}

{
  const item = {
    id:'testing', phase:'verify', file:'src/calc.ts', prompt:'Verify calculateTotal rounding',
    signals:{ symbol:'calculateTotal', technologies:['UnknownStack'] }
  };
  const session = sessionFor(item);
  const card = presentLearningCard(buildLearningExperience(stateFor(item.id), session, item.id).card, session);
  assert.match(card.question, /calculateTotal/i);
  assert.doesNotMatch(card.question, /Stripe|OAuth|PostgreSQL|Redis/i, `unknown context hallucinated a stack: ${card.question}`);
}

{
  const item = {
    id:'testing', phase:'verify', file:'src/large-task.ts',
    prompt:'Verify this behavior '.repeat(100), signals:{ symbol:'verifyLargeTask' }, seconds:8
  };
  const session = sessionFor(item);
  const card = presentLearningCard(buildLearningExperience(stateFor(item.id), session, item.id).card, session);
  assert.equal(card.presentation.depth, 'glance');
  assert.ok(card.seconds <= 12);
  assert.ok(card.question.length <= 240);
  assert.ok(card.why.length <= 145);
}

console.log(`IdleBench Corpus PASS · ${passed} domains + anti-hallucination + wait-window ergonomics`);
