import fs from 'node:fs';
import path from 'node:path';
import { projectPaths } from './paths.mjs';
import { ensureIdentity, signBytes, verifyBytes, verifyProvenanceChain, buildAgentBom } from './provenance.mjs';
import { policyHash, loadPolicy } from './policy.mjs';
import { responsibilityReport } from './ownership.mjs';

export const PREDICATE_TYPE = 'https://github.com/TFourniax/tooltest-2/spec/agentic-development-provenance/v1';
export const PAYLOAD_TYPE = 'application/vnd.in-toto+json';
function readJson(file, fallback = null) { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch (error) { if (error.code === 'ENOENT') return fallback; throw error; } }
function dssePae(payloadType, payloadBytes) { const type = Buffer.from(payloadType, 'utf8'); const payload = Buffer.from(payloadBytes); return Buffer.concat([Buffer.from(`DSSEv1 ${type.length} `, 'utf8'), type, Buffer.from(` ${payload.length} `, 'utf8'), payload]); }
function latestSession(state) { return Object.values(state?.sessions || {}).sort((a, b) => String(b.lastEventAt || '').localeCompare(String(a.lastEventAt || '')))[0] || null; }
function receiptSubject(receipt, cwd) { const digest = receipt?.session?.proof?.diffSha256; return [{ name: `${path.basename(path.resolve(cwd))}:working-tree-diff`, digest: { sha256: digest || '0'.repeat(64) } }]; }
export function buildStatement(cwd = process.cwd()) {
  const paths = projectPaths(cwd); const receipt = readJson(paths.receipt, { metrics: {}, session: null }); const diffDigest = receipt?.session?.proof?.diffSha256; if (!/^[a-f0-9]{64}$/.test(String(diffDigest || ''))) throw new Error('No completed agent turn with a diff proof is available to attest.');
  const state = readJson(paths.state, { sessions: {} }); const session = latestSession(state); const chain = verifyProvenanceChain(cwd); if (!chain.ok) throw new Error(`Provenance chain is invalid: ${chain.errors.join('; ')}`); const bom = buildAgentBom(cwd); const policy = loadPolicy(cwd); const responsibility = responsibilityReport(cwd); const identity = ensureIdentity(cwd); const findings = receipt?.session?.findings || session?.findings || []; const maxRisk = Math.max(0, ...(session?.events || []).map((event) => Number(event.policyRisk || 0)));
  return { _type: 'https://in-toto.io/Statement/v1', subject: receiptSubject(receipt, cwd), predicateType: PREDICATE_TYPE, predicate: { schema: 'idleproof.agentic-development-provenance.v1', generatedAt: new Date().toISOString(), project: path.basename(path.resolve(cwd)), sourceRevision: receipt?.session?.proof?.head || null, execution: { sessionId: receipt?.session?.id || session?.id || null, intent: receipt?.session?.intent || null, agentSource: receipt?.session?.source || session?.source || null, startedAt: receipt?.session?.startedAt || session?.startedAt || null, completedAt: receipt?.session?.completedAt || session?.completedAt || null, files: receipt?.session?.files || session?.touchedFiles || [], changed: receipt?.session?.changed || session?.changed || { added: 0, deleted: 0 }, maxObservedPolicyRisk: maxRisk }, controls: { policyProfile: policy.profile, policySha256: policyHash(cwd), findings: findings.map((finding) => ({ id: finding.id, severity: finding.severity, title: finding.title })), knowledgeDebt: receipt?.metrics?.debt ?? null, cognitiveCoverage: receipt?.metrics?.coverage ?? null }, provenance: { chainLength: chain.length, chainHeadSha256: chain.headHash, signerFingerprint: identity.fingerprint }, responsibility, agentBillOfMaterials: bom, environment: { node: process.version, platform: process.platform, arch: process.arch } } };
}
export function createAttestation(cwd = process.cwd()) { const statement = buildStatement(cwd); const payloadBytes = Buffer.from(JSON.stringify(statement), 'utf8'); const pae = dssePae(PAYLOAD_TYPE, payloadBytes); const signature = signBytes(cwd, pae); const identity = ensureIdentity(cwd); const envelope = { payloadType: PAYLOAD_TYPE, payload: payloadBytes.toString('base64'), signatures: [{ keyid: signature.keyid, sig: signature.sig }], verificationMaterial: { keyType: identity.keyType, publicKey: identity.publicKey, fingerprint: identity.fingerprint } }; fs.mkdirSync(projectPaths(cwd).dir, { recursive: true }); fs.writeFileSync(projectPaths(cwd).attestation, `${JSON.stringify(envelope, null, 2)}\n`, { encoding: 'utf8', mode: 0o600 }); return envelope; }
export function verifyAttestation(input, { expectedPublicKey = null } = {}) { const envelope = typeof input === 'string' ? JSON.parse(fs.readFileSync(input, 'utf8')) : input; if (!envelope || envelope.payloadType !== PAYLOAD_TYPE || !envelope.payload || !Array.isArray(envelope.signatures) || !envelope.signatures.length) return { ok: false, errors: ['Invalid DSSE envelope'] }; const payload = Buffer.from(envelope.payload, 'base64'); const pae = dssePae(envelope.payloadType, payload); const publicKey = expectedPublicKey || envelope.verificationMaterial?.publicKey; if (!publicKey) return { ok: false, errors: ['No public key available'] }; const signatureOk = envelope.signatures.some((signature) => verifyBytes(pae, signature.sig, publicKey)); let statement = null; const errors = []; if (!signatureOk) errors.push('Signature verification failed'); try { statement = JSON.parse(payload.toString('utf8')); } catch { errors.push('Payload is not valid JSON'); } if (statement?._type !== 'https://in-toto.io/Statement/v1') errors.push('Unexpected in-toto statement type'); if (statement?.predicateType !== PREDICATE_TYPE) errors.push('Unexpected IdleProof predicate type'); return { ok: errors.length === 0, signatureOk, statement, errors }; }
export function decodeAttestation(input) { const envelope = typeof input === 'string' ? JSON.parse(fs.readFileSync(input, 'utf8')) : input; return JSON.parse(Buffer.from(envelope.payload, 'base64').toString('utf8')); }
